image: php:8.2

pipelines:
  default:
    - parallel:
        - step:
            name: Install & Run Tests
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git zip libzip-dev libpng-dev libonig-dev libxml2-dev libicu-dev libfreetype6-dev libjpeg62-turbo-dev
              - docker-php-ext-install pdo pdo_mysql zip gd intl
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install --ignore-platform-reqs
              - ./vendor/bin/phpunit test
        - step:
            name: Lint
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git zip libzip-dev libpng-dev libonig-dev libxml2-dev libicu-dev libfreetype6-dev libjpeg62-turbo-dev
              - docker-php-ext-install pdo pdo_mysql zip gd intl
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install --ignore-platform-reqs

