<?php

/**
 * Create all permissions
 */
return [
    'Users Management' => [
        'Create Users',
        'View Users List',
        'View Users',
        'Edit Users',
        'Delete Users',
    ],
    'Role Management' => [
        'Create Roles',
        'View Roles List',
        'View Roles',
        'Edit Roles',
        'Delete Role',
    ],
    'Permissions Mang' => [
        'Create Permissions',
        'View Permissions List',
        'View Permissions',
        'Edit Permissions',
        'Delete Permissions',
    ],
    'Suppliers Management' => [
        'Create Suppliers',
        'View Suppliers List',
        'View Suppliers',
        'Edit Suppliers',
        'Delete Suppliers',
    ],
    'Vendors Management' => [
        'Create Vendors',
        'View Vendors List',
        'View Vendors',
        'Edit Vendors',
        'Delete Vendors',
    ],
    'Purchase Order' => [
        'Create Purchase Order',
        'View Purchase Order List',
        'View Purchase Order',
        'Edit Purchase Order',
        'Delete Purchase Order',
    ],
    'GRN' => [
        'Create GRN',
        'View GRN List',
        'View GRN',
        'Edit GRN',
        'Delete GRN',
    ],
    'Units' => [
        'Create Units',
        'View Units List',
        'View Units',
        'Edit Units',
        'Delete Units',
    ],
    'Processes' => [
        'Create Processes',
        'View Processes List',
        'View Processes',
        'Edit Processes',
        'Delete Processes',
    ],
    'Raw Materials' => [
        'Create Raw',
        'View Raw List',
        'View Raw',
        'Edit Raw',
        'Delete Raw',
    ],
    'Product' => [
        'Create Product',
        'View Product List',
        'View Product',
        'Edit Product',
        'Delete Product',
    ],
    'Formulation' => [
        'Create Formulation',
        'View Formulation',
        'View Formulation List',
        'Edit Formulation',
        'Delete Formulation',
    ],
    'Batches' => [
        'Create Batches',
        'View Batches',
        'View Batches List',
        'Edit Batches',
        'Delete Batches',
    ],
    'Goods-Issuance' => [
        'Create Goods-Issuance',
        'View Goods-Issuance List',
        'View Goods-Issuance',
        'Edit Goods-Issuance',
        'Delete Goods-Issuance',
    ],
    'Goods-Reciept' => [
        'Create Goods-Reciept',
        'View Goods-Reciept',
        'View Goods-Reciept List',
        'Edit Goods-Reciept',
        'Delete Goods-Reciept',
    ],
    'Packing' => [
        'Create Packing',
        'View Packing',
        'View Packing List',
        'Edit Packing',
        'Delete Packing',
    ],
    'Inventory' => [
        'Create Inventory',
        'View Inventory',
        'View Inventory List',
        'Edit Inventory',
        'Delete Inventory',
    ],
    'POS Orders' => [
        'Create POS Orders',
        'View POS Orders List',
        'View POS Orders',
        'Edit POS Orders',
        'Delete POS Orders',
    ],
    'Customers' => [
        'Create Customers',
        'View Customers List',
        'View Customers',
        'Edit Customers',
        'Delete Customers',
    ],
    'Categories' => [
        'View Categories',
        'Create Categories',
        'Edit Categories',
        'Delete Categories',
    ],
    'Packing Material' => [
        'View Packing Material',
        'Create Packing Material',
        'Edit Packing Material',
        'Delete Packing Material',
    ],
    'Groups' => [
        'View Groups',
        'Create Groups',
        'Edit Groups',
        'Delete Groups',
    ],
    'Ledgers' => [
        'View Ledgers',
        'Create Ledgers',
        'Edit Ledgers',
        'Delete Ledgers',
    ],
    'Voucher' => [
        'View Vouchers',
        'Create Vouchers',
        'Edit Vouchers',
        'Delete Vouchers',
    ],
    'Report' => [
        'View Reports',
        'Create Reports',
        'Edit Reports',
        'Delete Reports',
    ],
    'Companies' => [
        'View Companies',
        'Create Companies',
        'Edit Companies',
        'Delete Companies',
    ],
    'Branches' => [
        'View Branches',
        'Create Branches',
        'Edit Branches',
        'Delete Branches',
    ],
    'Countries' => [
        'View Countries',
        'Create Countries',
        'Edit Countries',
        'Delete Countries',
    ],
    'City' => [
        'View City',
        'Create City',
        'Edit City',
        'Delete City',
    ],
    'Staff' => [
        'View Staff',
        'Create Staff',
        'Edit Staff',
        'Delete Staff',
    ],
    'Entries' => [
        'View Enties',
    ],
    'Holidays' => [
        'View Holidays',
        'Create Holidays',
        'Edit Holidays',
        'Delete Holidays',
    ],
    'Leave Types' => [
        'View Leave Types',
        'Create Leave Types',
        'Edit Leave Types',
        'Delete Leave Types',
    ],
    'Leave Entitlement' => [
        'View Leave Entitlement',
        'Create Leave Entitlement',
        'Edit Leave Entitlement',
        'Delete Leave Entitlement',
    ],
    'Leave Requests' => [
        'View Leave Requests',
        'Create Leave Requests',
        'Edit Leave Requests',
        'Delete Leave Requests',
    ],
    'Leaves' => [
        'View Leaves',
        'Create Leaves',
        'Edit Leaves',
        'Delete Leaves',
    ],
    'Leave Statuses' => [
        'View Leave Statuses',
        'Create Leave Statuses',
        'Edit Leave Statuses',
        'Delete Leave Statuses',
    ],
    'Loan Plans' => [
        'View Loan Plans',
        'Create Loan Plans',
        'Edit Loan Plans',
        'Delete Loan Plans',
    ],
    'Loans' => [
        'View Loans',
        'Create Loans',
        'Edit Loans',
        'Delete Loans',
    ],
    'Work Shifts' => [
        'View Work Shifts',
        'Create Work Shifts',
        'Edit Work Shifts',
        'Delete Work Shifts',
    ],

    'Work Weeks' => [
        'View Work Weeks',
        'Create Work Weeks',
        'Edit Work Weeks',
        'Delete Work Weeks',
    ],
];
